from typing import Any, Dict

THEMES: dict[str, list[str]] = {
    "No theme (raw)": ["", "", ""],
    "Cinematic photo": [
        "a cinematic photograph, soft natural light",
        "a cinematic photograph with shallow depth of field, soft rim lighting, 35mm lens, subtle film grain",
        "an award-winning cinematic photograph at golden hour, shallow depth (f/2.2), volumetric light, 35mm film grain, rich color grading",
    ],
    "Watercolor illustration": [
        "a watercolor illustration",
        "a watercolor illustration on textured cold-press paper, soft gradients and pigment blooms",
        "a hand-painted watercolor illustration on textured cold-press paper, pigment blooms, soft edges, gentle washes, natural paper grain",
    ],
    "Isometric vector": [
        "a clean isometric vector illustration",
        "a minimalist isometric vector illustration, pastel palette, crisp lines, no gradients",
        "a clean isometric vector illustration, pastel flat colors, crisp lines, geometric forms, no gradients, generous white space",
    ],
    "Product studio render": [
        "a studio product photograph",
        "a studio product photo, softbox lighting, seamless gradient backdrop",
        "a high-end studio product photo, dual softboxes, seamless gradient backdrop, subtle reflection, photoreal materials",
    ],
    "Cyberpunk neon": [
        "a cyberpunk night scene",
        "a cyberpunk night scene, neon signage, rain-wet streets, reflections, teal-magenta palette",
        "a cinematic cyberpunk night scene, dense neon signage, rain-wet bokeh, reflections, teal-magenta palette, atmospheric haze",
    ],
    "Pixel art": [
        "retro pixel art",
        "retro pixel art, 32–64 px sprite scale, limited palette",
        "retro pixel art, 32–64 px sprite scale, 16-color palette, 1px outlines, NES-style",
    ],
    "Low-poly 3D": [
        "a low-poly 3D render",
        "a low-poly 3D render, flat shading, soft ambient occlusion",
        "a low-poly 3D render, flat shading, soft ambient occlusion, pastel palette, studio lighting",
    ],
    "Line art icon": [
        "a minimal line icon",
        "a minimal line icon, single-weight strokes, monochrome, centered on white",
        "a minimal line icon, single-weight strokes, monochrome, geometric balance, centered, no fill",
    ],
}
DEFAULTS: Dict[str, Any] = {
    "motif": "simple seasonal icon",
    "background_treatment": "soft neutral wash",
    "illustration_style": "hand-painted watercolor with subtle vector refinement",
    "botanical_motifs": "eucalyptus sprigs",
    "animal_motifs": "none",
    "rim_style": "thin gold rim",
    "background_library": "pastel wash, faint diagonal stripes",
    "base_tones": "ivory, cream",
    "accent_colors": "sage, muted coral",
    "metallic_finish": "subtle gold foil",
    "decorative_florals": "natural sprigs (sparse)",
    "decorative_icons": "tiny stars or dots",
    "border_style": "clean single-line rim",
    "finish_spec": "matte with selective glossy accents",
    "aspect": "square",
    "size_hint": "cocktail napkin (5×5in)",
    "quality_hint": "hd",
    "typography_style": "elegant sans or light script",
    "typography_placement": "small near rim",
    "typography_color": "neutral or metallic",
    "theme_notes": "Keep composition uncluttered and print-friendly.",
    "use_typography": "no",
    "typography_copy": "",
    # Anti-crowding
    "coverage_target": "30%",
    "min_margin_each_side": "25%",
    "max_floral_clusters": "3",
    "max_icon_count": "2",
}

THEMES_PRESETS_MIN: Dict[str, Dict[str, Any]] = {
    "🌸 Spring Garden Wedding": {
        "motif": "watercolor peony-and-lavender floral wreath",
        "background_treatment": "soft blush pastel wash",
        "illustration_style": "hand-painted watercolor with delicate linework",
        "botanical_motifs": "lavender sprigs, peonies, eucalyptus",
        "animal_motifs": "none",
        "rim_style": "thin scalloped edge with delicate gold foil accent",
        "background_library": "pastel wash, faint diagonal stripes",
        "base_tones": "blush pink, cream, ivory",
        "accent_colors": "sage green, lavender",
        "metallic_finish": "gold foil accents",
        "decorative_florals": "flowing natural sprigs only less than 3 clusters",
        "decorative_icons": "tiny bows or petals (sparingly) max 2",
        "border_style": "simple gold rim, no repeating motifs",
        "finish_spec": "matte base with selective glossy floral highlights",
        "aspect": "square",
        "api_size": "1024x1024",
        "quality_hint": "hd",
        "typography_style": "calligraphic script",
        "typography_placement": "subtle rim placement",
        "typography_color": "metallic gold",
        "theme_notes": "Wedding elegance; keep palette airy and romantic.",
        "use_typography": "no",
        "typography_copy": "",
    },
    "🐇 Woodland Birthday": {
        "motif": "whimsical bunny illustration with floral sprigs",
        "background_treatment": "soft diagonal stripe",
        "illustration_style": "realistic sketch with soft watercolor fill",
        "botanical_motifs": "wildflowers, lavender",
        "animal_motifs": "bunny, small songbirds",
        "rim_style": "rounded rim with soft gold foil edge",
        "background_library": "soft stripes, pastel wash",
        "base_tones": "pastels—lavender, blush, cream",
        "accent_colors": "sunshine yellow, turquoise",
        "metallic_finish": "gold shimmer accents",
        "decorative_florals": "hand-painted sprigs",
        "decorative_icons": "stars and tiny bows",
        "border_style": "minimal gold rim, no repeats",
        "finish_spec": "matte with glossy highlights on motif",
        "aspect": "square",
        "api_size": "1024x1024",
        "quality_hint": "standard",
        "typography_style": "rounded friendly",
        "typography_placement": "small banner below motif",
        "typography_color": "deep green",
        "theme_notes": "Child-friendly but elegant; avoid clutter.",
        "use_typography": "no",
        "typography_copy": "",
    },
    "🦌 Festive Holiday": {
        "motif": "regal deer with holly vines and red berries",
        "background_treatment": "ivory with subtle gradient fade",
        "illustration_style": "detailed watercolor with precise linework",
        "botanical_motifs": "holly, evergreen sprigs",
        "animal_motifs": "deer, winter birds",
        "rim_style": "slim circular gold foil rim",
        "background_library": "muted gradient, light pastel wash",
        "base_tones": "ivory, taupe",
        "accent_colors": "berry red, deep green",
        "metallic_finish": "rich gold foil",
        "decorative_florals": "holly sprigs",
        "decorative_icons": "snowflakes (minimal)",
        "border_style": "clean gold rim only (no repeats or emboss)",
        "finish_spec": "glossy highlights on metallics, matte base",
        "aspect": "square",
        "api_size": "1024x1024",
        "quality_hint": "hd",
        "typography_style": "elegant calligraphy",
        "typography_placement": "integrated along the rim",
        "typography_color": "metallic gold or berry red",
        "theme_notes": "Premium holiday tone; emphasize contrast and foil.",
        "use_typography": "no",
        "typography_copy": "",
    },
    "✨ Luxury Dinner": {
        "motif": "minimalist geometric center medallion",
        "background_treatment": "deep charcoal black",
        "illustration_style": "modern vector with subtle bevel",
        "botanical_motifs": "none",
        "animal_motifs": "none",
        "rim_style": "precise thin gold rim",
        "background_library": "flat or micro-texture",
        "base_tones": "black, charcoal",
        "accent_colors": "gold only, minimal",
        "metallic_finish": "high-polish gold",
        "decorative_florals": "none",
        "decorative_icons": "none",
        "border_style": "none (keep border area plain)",
        "finish_spec": "glossy metallic on matte base",
        "aspect": "square",
        "api_size": "1024x1024",
        "quality_hint": "hd",
        "typography_style": "none",
        "typography_placement": "none",
        "typography_color": "gold",
        "theme_notes": "Keep ultra-minimal; rely on contrast and finish.",
        "use_typography": "no",
        "typography_copy": "",
    },
    "🌴 Tropical Party": {
        "motif": "palm leaves and hibiscus floral ring",
        "background_treatment": "turquoise wash with subtle grain",
        "illustration_style": "vibrant watercolor + vector clean-up",
        "botanical_motifs": "palm, monstera, hibiscus",
        "animal_motifs": "butterflies or tropical birds (sparingly)",
        "rim_style": "thin gold foil rim with very light floral accent",
        "background_library": "pastel wash, subtle grain, soft stripes",
        "base_tones": "turquoise, ivory",
        "accent_colors": "sunshine yellow, berry red",
        "metallic_finish": "gold foil accents",
        "decorative_florals": "loose hand-painted leaves",
        "decorative_icons": "tiny stars (optional)",
        "border_style": "subtle gold rim only",
        "finish_spec": "matte base with selective glossy floral highlights",
        "aspect": "square",
        "api_size": "1024x1024",
        "quality_hint": "standard",
        "typography_style": "friendly rounded",
        "typography_placement": "subtle banner or lower rim",
        "typography_color": "gold or deep green",
        "theme_notes": "Lively and premium; avoid over-saturation.",
        "use_typography": "no",
        "typography_copy": "",
    },
    "🍔 Backyard BBQs / Cookouts": {
        "motif": "grill silhouette with tongs",
        "background_treatment": "warm parchment wash",
        "base_tones": "warm ivory, parchment",
        "accent_colors": "tomato red, charcoal gray",
        "botanical_motifs": "rosemary sprigs",
        "theme_notes": "Casual outdoor vibe; avoid heavy smoke textures.",
    },
    "🏊‍♂️ Pool parties": {
        "motif": "retro pool float and wave line",
        "background_treatment": "aqua gradient wash",
        "base_tones": "pale aqua, porcelain",
        "accent_colors": "teal, sunshine yellow",
        "theme_notes": "Fresh, airy, light splash shapes only.",
    },
    "🐣 Easter brunches": {
        "motif": "delicate egg motif with tiny florals",
        "background_treatment": "pastel blush wash",
        "base_tones": "blush, cream",
        "accent_colors": "lavender, mint",
        "botanical_motifs": "tulips, lavender",
        "theme_notes": "Soft spring mood; keep corners empty.",
    },
    "🎃 Halloween parties": {
        "motif": "minimal moon with tiny bats",
        "background_treatment": "soft charcoal fog (light)",
        "base_tones": "off-black, bone",
        "accent_colors": "pumpkin orange, antique gold",
        "theme_notes": "Keep spooky minimal; no blood or gore.",
    },
    "🎉 New Year’s brunch": {
        "motif": "sparkler burst with star confetti",
        "background_treatment": "pearl sheen wash",
        "base_tones": "pearl, soft gray",
        "accent_colors": "champagne, midnight blue",
        "metallic_finish": "fine gold foil",
        "theme_notes": "Elevated celebration; crisp, high contrast.",
    },
    "💼 Farewell or promotion parties at work": {
        "motif": "rising arrow ribbon with tiny stars",
        "background_treatment": "clean ivory wash",
        "base_tones": "ivory, pale stone",
        "accent_colors": "royal blue, soft gold",
        "theme_notes": "Professional, optimistic; keep tone refined.",
    },
}
